#! /bin/bash

if [ $# -eq 0 ]; then
    kubectl get secret -o=json | jq -r '.items[].metadata.name'
    exit 0
fi

kubectl get secret $1 -o=json | jq -r '.data | keys[] as $k | "\($k): \(.[$k] | @base64d)"'
